### ISSUE TITLE
Remote branch 2.0.4 not found in upstream origin

### ISSUE THREAD

**Issue by alxndr** [saadparwaiz1/homebrew-personal#21]
Hi, thanks for making this tap!

When I try to `brew install saadparwaiz1/personal/lua-language-server` (on OS X) I receive the above error during the `git clone`.

**Comment by saadparwaiz1** [comment]
try doing `brew tap saadparwaiz1/personal` and then try installing it as `brew install lua-language-server`. Can you also let me know what the output of `brew doctor` is

**Comment by saadparwaiz1** [comment]
Should be fixed in the next commit 😁

**Comment by saadparwaiz1** [comment]
is fixed now :)
