### ISSUE TITLE
Remote branch 2.2.0 not found in upstream origin

### ISSUE THREAD

**Issue by aleksanderEE** [saadparwaiz1/homebrew-personal#23]
I guess it would be best to use sha instead of branch names as they seem to be regularly deleted by @sumneko

**Comment by saadparwaiz1** [comment]
I usually use version tags. I was going to make a pull request updating this tap soon which should fix it. I'll look into using sha as soon as I get some free time :)

**Comment by saadparwaiz1** [comment]
The error shouldn't occur if you are using the bottle to install the server or are you trying to build it from source?

**Comment by aleksandersumowski** [comment]
from personal account, I was installing it from your tap, following the README

the tag in Formulae pointed to 2.2.0 branch which is now deleted
I ended up installing from source which worked without issues

**Comment by saadparwaiz1** [comment]
ah ok. yeah I'll try to make sure the tap is updated often so it doesn't happen :)
